version: 2
jobs:
  test:
    working_directory: ~/
    docker:
      -image: circleci/node:12.12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  test:
    jobs:
      - test
