version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: npm run test

workflows:
  test-flow:
      jobs:
        - test
